# Generated by Django 4.2.1 on 2023-06-02 03:42

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CustomUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "username",
                    models.CharField(blank=True, max_length=50, null=True, verbose_name="ユーザー名"),
                ),
                ("line_id", models.CharField(max_length=30, unique=True, verbose_name="LINE ID")),
            ],
        ),
    ]
