# Generated by Django 4.2.1 on 2023-06-02 04:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_unknownmessage"),
    ]

    operations = [
        migrations.CreateModel(
            name="GreetingMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("text", models.TextField()),
            ],
        ),
    ]
