# Generated by Django 4.2.1 on 2023-06-02 05:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0005_smartpoll_alter_greetingmessage_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="buddyinformation",
            name="buddy_name",
            field=models.CharField(default="", max_length=50, verbose_name="バディーネーム"),
        ),
        migrations.AddField(
            model_name="buddyinformation",
            name="buddy_sage",
            field=models.IntegerField(
                default=20,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(130),
                ],
                verbose_name="バディーの年齢",
            ),
        ),
    ]
