# Generated by Django 4.2.1 on 2023-06-02 06:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0006_buddyinformation_buddy_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="buddyinformation",
            name="buddy_name",
            field=models.CharField(blank=True, max_length=50, verbose_name="バディーネーム"),
        ),
    ]
