# Generated by Django 4.2.1 on 2023-06-02 16:11

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0007_alter_buddyinformation_buddy_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserPollRelation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("poll_name", models.CharField(blank=True, max_length=50, verbose_name="ポールの名前")),
                (
                    "poll_age",
                    models.IntegerField(
                        default=20,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(130),
                        ],
                        verbose_name="ポールの年齢",
                    ),
                ),
                (
                    "smart_poll",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_relation",
                        to="api.smartpoll",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="poll_relation",
                        to="api.customuser",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "バディー情報",
            },
        ),
        migrations.DeleteModel(
            name="buddyInformation",
        ),
    ]
