# Generated by Django 4.2.1 on 2023-06-02 16:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0008_userpollrelation_delete_buddyinformation"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userpollrelation",
            options={"verbose_name_plural": "ユーザとポールの関係"},
        ),
    ]
