# Generated by Django 4.2.1 on 2023-06-08 05:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0014_responsemessage_alter_greetingmessage_text_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userpollrelation",
            name="is_buddy",
            field=models.BooleanField(default=False, verbose_name="バディかどうか"),
        ),
        migrations.AddField(
            model_name="userpollrelation",
            name="is_primary",
            field=models.BooleanField(default=False, verbose_name="プライマリー指定"),
        ),
    ]
