# Generated by Django 4.2.1 on 2023-06-10 13:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0015_userpollrelation_is_buddy_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserSequence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "is_change_user_name",
                    models.BooleanField(default=False, verbose_name="ユーザの名前を変更中か"),
                ),
                (
                    "is_change_poll_name",
                    models.BooleanField(default=False, verbose_name="ポールの名前を変更中か"),
                ),
                (
                    "is_change_poll_age",
                    models.BooleanField(default=False, verbose_name="ポールの年齢を変更中か"),
                ),
                (
                    "is_change_poll_gender",
                    models.BooleanField(default=False, verbose_name="ポールの性別を変更中か"),
                ),
            ],
        ),
        migrations.AddField(
            model_name="userpollrelation",
            name="poll_gender",
            field=models.IntegerField(
                blank=True,
                choices=[(1, "男性"), (2, "女性"), (3, "その他")],
                null=True,
                verbose_name="ポールの性別",
            ),
        ),
    ]
