# Generated by Django 4.2.1 on 2023-06-10 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0016_usersequence_userpollrelation_poll_gender"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersequence",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_sequence",
                to="api.customuser",
            ),
            preserve_default=False,
        ),
    ]
