# Generated by Django 4.2.1 on 2023-06-10 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0017_usersequence_user"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="usersequence",
            options={"verbose_name_plural": "ユーザの状態"},
        ),
        migrations.AddField(
            model_name="usersequence",
            name="target",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="relation_sequence",
                to="api.userpollrelation",
            ),
        ),
    ]
