# Generated by Django 4.2.1 on 2023-06-17 14:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0019_customuser_created_at_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userpollcommentcount",
            options={"verbose_name_plural": "ユーザが特定のポールを呼びかけた回数"},
        ),
        migrations.RemoveField(
            model_name="userpollcommentcount",
            name="user_comment_count",
        ),
        migrations.AddField(
            model_name="userpollcommentcount",
            name="count_in_level",
            field=models.IntegerField(default=0, verbose_name="親密度変化後の合計値"),
        ),
        migrations.AddField(
            model_name="userpollcommentcount",
            name="total",
            field=models.IntegerField(default=0, verbose_name="累計"),
        ),
    ]
