# Generated by Django 4.2.1 on 2023-06-17 15:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0020_alter_userpollcommentcount_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userpollcommentcount",
            name="continuous_day_in_level",
            field=models.IntegerField(default=0, verbose_name="連続話しかけ日数"),
        ),
    ]
