# Generated by Django 4.2.1 on 2023-06-18 06:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0022_responsemessage_poll_gender_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="responsemessage",
            name="poll_generation",
        ),
        migrations.AddField(
            model_name="responsemessage",
            name="poll_age_max",
            field=models.IntegerField(default=130, verbose_name="ポールの年齢の最大値"),
        ),
        migrations.AddField(
            model_name="responsemessage",
            name="poll_age_min",
            field=models.IntegerField(default=0, verbose_name="ポールの年齢の最小値"),
        ),
    ]
