# Generated by Django 4.2.1 on 2023-06-18 07:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0024_remove_responsemessage_relationship_level_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="responsemessage",
            name="poll_gender",
            field=models.IntegerField(
                choices=[(1, "男性"), (2, "女性"), (3, "その他")], default=3, verbose_name="ポールの性別"
            ),
        ),
    ]
