# Generated by Django 4.2.1 on 2023-07-31 14:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0026_remove_usersequence_is_change_poll_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="responsemessage",
            name="relationship_level_max",
            field=models.IntegerField(default=5, verbose_name="親密度の最大値"),
        ),
        migrations.AlterField(
            model_name="responsemessage",
            name="relationship_level_min",
            field=models.IntegerField(default=1, verbose_name="親密度の最小値"),
        ),
    ]
