# Generated by Django 4.2.1 on 2023-08-01 07:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0027_alter_responsemessage_relationship_level_max_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="responsemessage",
            name="poll_gender",
            field=models.IntegerField(
                choices=[(1, "男性"), (2, "女性"), (3, "秘密")], default=3, verbose_name="ポールの性別"
            ),
        ),
        migrations.AlterField(
            model_name="userpollrelation",
            name="poll_gender",
            field=models.IntegerField(
                blank=True,
                choices=[(1, "男性"), (2, "女性"), (3, "秘密")],
                null=True,
                verbose_name="ポールの性別",
            ),
        ),
    ]
